# Generated by Django 5.2.17 on 2026-10-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('Main Course', 'Main Course'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks'), ('Dessert', 'Dessert')], max_length=20),
        ),
    ]
